name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PySide6 numpy scipy librosa
          pip install pyqtgraph SQLAlchemy faiss-cpu onnxruntime sentence-transformers
          pip install pytest pytest-qt sentry-sdk
          pip install numba llvmlite soundfile audioread soxr scikit-learn joblib

      - name: Download FFmpeg static binary
        run: |
          if not exist src\resources\ffmpeg mkdir src\resources\ffmpeg
          curl -L "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip" -o ffmpeg.zip
          7z x ffmpeg.zip
          move ffmpeg-master-latest-win64-gpl\bin\ffmpeg.exe src\resources\ffmpeg\
          del ffmpeg.zip
          rmdir /s /q ffmpeg-master-latest-win64-gpl
        shell: cmd

      - name: Display spec file content (for debugging)
        run: |
          echo "--- bina_cshera.spec ---"
          type bina_cshera.spec 
          echo "--- End of spec file ---"

      - name: Build executable with PyInstaller
        run: pyinstaller --log-level DEBUG bina_cshera.spec

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: BinaKshera-Windows-EXE
          path: dist/bina_cshera/

      - name: Upload Build Directory artifact (for debugging)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: PyInstaller-Build-Dir-Windows
          path: build/bina_cshera/
